"""HAProxy configuration helpers for Leyzen Vault."""

from __future__ import annotations

from typing import Mapping, Sequence

from vault_plugins import VaultServicePlugin


def resolve_backend_port(env: Mapping[str, str], plugin: VaultServicePlugin) -> int:
    """Return the backend port for the active plugin."""

    override = env.get("VAULT_WEB_PORT", "").strip()
    if override:
        try:
            port = int(override)
        except ValueError:
            port = None
        else:
            if port is not None and 1 <= port <= 65535:
                return port
    plugin_port = getattr(plugin, "web_port", 80)
    try:
        port = int(plugin_port)
    except (TypeError, ValueError):
        return 80
    if port is not None and 1 <= port <= 65535:
        return port
    return 80


def _format_backend_servers(containers: Sequence[str], port: int) -> list[str]:
    lines: list[str] = []
    for name in containers:
        lines.append(f"    server {name} {name}:{port} check")
    if not lines:
        lines.append("    # No backend servers configured")
    return lines


def render_haproxy_config(
    plugin: VaultServicePlugin,
    containers: Sequence[str],
    port: int,
    *,
    enable_https: bool = False,
    ssl_cert_path: str | None = None,
    ssl_key_path: str | None = None,
) -> str:
    """Return the HAProxy configuration for the supplied plugin.

    Args:
        plugin: The active vault service plugin.
        containers: List of container names for the backend servers.
        port: Backend port number.
        enable_https: If True, enable HTTPS frontend on port 443.
        ssl_cert_path: Path to SSL certificate file (PEM format, can be combined cert+key).
                      Used only if enable_https is True.
        ssl_key_path: Path to SSL private key file (if separate from cert).
                      Used only if enable_https is True and cert is not combined.

    Returns:
        HAProxy configuration string.
    """
    backend_name = f"{plugin.name}_backend"
    server_lines = _format_backend_servers(containers, port)
    healthcheck_path = plugin.backend_healthcheck_path
    healthcheck_host = plugin.backend_healthcheck_host
    http_check_line = (
        f"    http-check send meth GET uri {healthcheck_path} ver HTTP/1.1"
        f" hdr Host {healthcheck_host}"
    )

    lines = [
        "# ==================================================================================",
        "# WARNING: This file is auto-generated by compose/haproxy_config.py",
        "# Do NOT edit this file manually. Instead, modify:",
        "#   - compose/haproxy_config.py for HAProxy configuration logic",
        "#   - vault_plugins/*/plugin.py for plugin-specific routing",
        "#   - Then run: python compose/build.py",
        "# ==================================================================================",
        "",
        "global",
        "    log stdout format raw local0",
        "    maxconn 4096",
        "",
        "resolvers docker",
        "    nameserver dns1 127.0.0.11:53",
        "    resolve_retries       3",
        "    timeout resolve        1s",
        "    timeout retry          1s",
        "    hold valid            10s",
        "",
        "defaults",
        "    log     global",
        "    mode    http",
        "    option  httplog",
        "    option  dontlog-normal",
        "    option  dontlognull",
        "    default-server init-addr none resolvers docker",
        "    timeout connect 5s",
        "    timeout client  50s",
        "    timeout server  50s",
        "",
        "http-errors myerrors",
        "    errorfile 503 /usr/local/etc/haproxy/503.http",
        "    errorfile 404 /usr/local/etc/haproxy/404.http",
        "",
        "frontend http_front",
        "    bind *:80",
        "    errorfiles myerrors",
        "    http-response return status 404 errorfile /usr/local/etc/haproxy/404.http if { status 404 }",
        "    http-request set-header X-Forwarded-Proto https if { ssl_fc }",
        '    http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains" if { ssl_fc }',
        "",
        "    acl path_orchestrator path_beg /orchestrator",
        "    use_backend orchestrator_backend if path_orchestrator",
        "",
        f"    default_backend {backend_name}",
        "",
    ]

    # Add HTTPS frontend if enabled
    if enable_https and ssl_cert_path:
        # Determine SSL bind configuration
        # HAProxy supports PEM files with combined cert+key, or separate cert/key files
        if ssl_key_path:
            # Separate cert and key files
            ssl_bind = f"    bind *:443 ssl crt {ssl_cert_path} key {ssl_key_path}"
        else:
            # Combined PEM file (cert+key)
            ssl_bind = f"    bind *:443 ssl crt {ssl_cert_path}"

        lines.extend(
            [
                "# HTTPS frontend - SSL/TLS termination",
                "frontend https_front",
                ssl_bind,
                "    errorfiles myerrors",
                "    http-response return status 404 errorfile /usr/local/etc/haproxy/404.http if { status 404 }",
                "    http-request set-header X-Forwarded-Proto https",
                '    http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains"',
                "",
                "    acl path_orchestrator path_beg /orchestrator",
                "    use_backend orchestrator_backend if path_orchestrator",
                "",
                f"    default_backend {backend_name}",
                "",
            ]
        )

    lines.extend(
        [
            f"backend {backend_name}",
            "    balance roundrobin",
            "    option http-server-close",
            "    option forwardfor header X-Forwarded-For if-none",
            "    default-server resolvers docker init-addr none check",
            "    option httpchk",
            http_check_line,
        ]
    )
    lines.extend(server_lines)
    lines.extend(
        [
            "",
            "backend orchestrator_backend",
            "    option http-server-close",
            "    option forwardfor header X-Forwarded-For if-none",
            "    default-server resolvers docker init-addr none check",
            "    server orchestrator orchestrator:80",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


__all__ = ["render_haproxy_config", "resolve_backend_port"]
