package compose

import (
	"fmt"
	"strings"
)

// RenderHAProxyConfig generates the HAProxy configuration string
func RenderHAProxyConfig(
	containers []string,
	port int,
	enableHTTPS bool,
	sslCertPath string,
	orchestratorEnabled bool,
) string {
	var sb strings.Builder

	sb.WriteString("# ==================================================================================\n")
	sb.WriteString("# WARNING: This file is auto-generated by leyzenctl config generate\n")
	sb.WriteString("# Do NOT edit this file manually.\n")
	sb.WriteString("# ==================================================================================\n\n")

	sb.WriteString("global\n")
	sb.WriteString("    log stdout format raw local0\n")
	sb.WriteString("    maxconn 4096\n\n")

	sb.WriteString("resolvers docker\n")
	sb.WriteString("    nameserver dns1 127.0.0.11:53\n")
	sb.WriteString("    resolve_retries       3\n")
	sb.WriteString("    timeout resolve        1s\n")
	sb.WriteString("    timeout retry          1s\n")
	sb.WriteString("    hold valid            10s\n\n")

	sb.WriteString("defaults\n")
	sb.WriteString("    log     global\n")
	sb.WriteString("    mode    http\n")
	sb.WriteString("    option  dontlog-normal\n")
	sb.WriteString("    option  dontlognull\n")
	sb.WriteString("    default-server init-addr none resolvers docker\n")
	sb.WriteString("    timeout connect 5s\n")
	sb.WriteString("    timeout client  50s\n")
	sb.WriteString("    timeout server  50s\n")
	sb.WriteString("    timeout check 5s\n\n")

	sb.WriteString("http-errors myerrors\n")
	sb.WriteString("    errorfile 503 /usr/local/etc/haproxy/errors/503.http\n")
	sb.WriteString("    errorfile 404 /usr/local/etc/haproxy/errors/404.http\n\n")

	sb.WriteString("frontend http_front\n")
	sb.WriteString("    bind *:80\n")
	sb.WriteString("    errorfiles myerrors\n")
	sb.WriteString("    http-request set-var(txn.is_api) bool(true) if { path_beg /api }\n")
	sb.WriteString("    http-response return status 404 content-type text/html file /usr/local/etc/haproxy/errors/404.http if { status 404 } !{ var(txn.is_api) -m bool }\n")
	sb.WriteString("    http-request set-header X-Forwarded-Proto https if { ssl_fc }\n")
	sb.WriteString("    http-response set-header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" if { ssl_fc }\n")
	sb.WriteString("    http-response set-header X-Content-Type-Options \"nosniff\"\n")
	sb.WriteString("    http-response set-header X-Frame-Options \"DENY\"\n")
	sb.WriteString("    http-response set-header X-XSS-Protection \"1; mode=block\"\n")
	sb.WriteString("    http-response set-header Referrer-Policy \"strict-origin-when-cross-origin\"\n\n")

	if orchestratorEnabled {
		sb.WriteString("    acl path_orchestrator path_beg /orchestrator\n")
		sb.WriteString("    use_backend orchestrator_backend if path_orchestrator\n\n")
	}

	sb.WriteString("    default_backend vault_backend\n\n")

	if enableHTTPS && sslCertPath != "" {
		sb.WriteString("# HTTPS frontend - SSL/TLS termination\n")
		sb.WriteString("frontend https_front\n")
		sb.WriteString(fmt.Sprintf("    bind *:443 ssl crt %s\n", sslCertPath))
		sb.WriteString("    errorfiles myerrors\n")
		sb.WriteString("    http-request set-var(txn.is_api) bool(true) if { path_beg /api }\n")
		sb.WriteString("    http-response return status 404 content-type text/html file /usr/local/etc/haproxy/errors/404.http if { status 404 } !{ var(txn.is_api) -m bool }\n")
		sb.WriteString("    http-request set-header X-Forwarded-Proto https\n")
		sb.WriteString("    http-response set-header Strict-Transport-Security \"max-age=31536000; includeSubDomains\"\n")
		sb.WriteString("    http-response set-header X-Content-Type-Options \"nosniff\"\n")
		sb.WriteString("    http-response set-header X-Frame-Options \"DENY\"\n")
		sb.WriteString("    http-response set-header X-XSS-Protection \"1; mode=block\"\n")
		sb.WriteString("    http-response set-header Referrer-Policy \"strict-origin-when-cross-origin\"\n\n")

		if orchestratorEnabled {
			sb.WriteString("    acl path_orchestrator path_beg /orchestrator\n")
			sb.WriteString("    use_backend orchestrator_backend if path_orchestrator\n\n")
		}
		sb.WriteString("    default_backend vault_backend\n\n")
	}

	sb.WriteString("backend vault_backend\n")
	sb.WriteString("    balance roundrobin\n")
	sb.WriteString("    option http-server-close\n")
	sb.WriteString("    option forwardfor header X-Forwarded-For if-none\n")
	sb.WriteString("    option redispatch\n")
	sb.WriteString("    option allbackups\n")
	sb.WriteString("    default-server resolvers docker init-addr last,libc,none check inter 3s fall 3 rise 2\n")
	sb.WriteString("    option httpchk\n")
	sb.WriteString("    http-check send meth GET uri /healthz ver HTTP/1.1 hdr Host localhost\n")
	sb.WriteString("    http-check expect status 200\n")

	for _, name := range containers {
		sb.WriteString(fmt.Sprintf("    server %s %s:%d check\n", name, name, port))
	}
	if len(containers) == 0 {
		sb.WriteString("    # No backend servers configured\n")
	}
	sb.WriteString("\n")

	if orchestratorEnabled {
		sb.WriteString("backend orchestrator_backend\n")
		sb.WriteString("    option http-server-close\n")
		sb.WriteString("    option forwardfor header X-Forwarded-For if-none\n")
		sb.WriteString("    default-server resolvers docker init-addr last,libc,none check\n")
		sb.WriteString("    server orchestrator orchestrator:80\n\n")
	}

	return sb.String()
}
